### Site Settings ###
title               : mayankmusaddi
description         : >-
                      Welcome to the digital realm where my thought meets pixels.
                      AI Engineer turning bytes into brilliance.
baseurl             : ""
repository          : mayankmusaddi/mayankmusaddi.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md  


### Author Info ###
author:
  name              : Mayank Musaddi
  image             : assets/profile.jpg
  email             : musaddi97@gmail.com
  facebook          : mayank.musaddi.7
  github            : mayankmusaddi
  linkedin          : mayank-musaddi-19b651172
  twitter           : mayank_musaddi
# behance           : your_username
# dribbble          : your_username
# gitlab            : your_usernames
# instagram         : your_username
# kaggle            : your_username
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name      


### Disqus ###
disqus:
  shortname: mayankmusaddi-github-io.disqus.com


### Analytics ###`
analytics:
  enabled: true
  google:
    tracking_id: UA-204818566-1


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"                        
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
